name: Build and deploy ASP.Net Core app to Azure Web App - TABP-App

on:
  push:
    branches:
      
development
workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  DOTNET_CORE_VERSION: '9.0.x'

jobs:
  build:
    runs-on: windows-latest
    steps:
      
uses: actions/checkout@v4

      
name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      
name: Restore
      run: dotnet restore TABP/TABP.sln

      
name: Build
      run: dotnet build TABP/TABP.sln --configuration Release --no-restore

      
name: Publish
      run: dotnet publish TABP/TABP.API/TABP.API.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      
name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      
name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      
name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'TABP-App'
        slot-name: 'Production'
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AC6FF4270B744819BF8C6E9B49267054 }}
