name: Build and Test

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore TABP/TABP.sln

      - name: Build solution
        run: dotnet build TABP/TABP.sln --no-restore --configuration Release

      - name: Run unit tests
        run: |
          dotnet test TABP/TABP.Application.Tests/TABP.Application.Tests.csproj --no-build --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"
